name: Give a bath
description: Start a bath challenge. Just click Submit, no typing needed.
title: Bath the cat
labels: ['game-action']
body:
  - type: markdown
    attributes:
      value: |
        <!-- action: bath -->
        I'm starting the bath challenge. 👉 Just click **Submit new issue**, no other input required.
