name: Close
description: Return to idle by clicking the info bar. Just click Submit, no typing needed.
title: Close
labels: ['game-action']
body:
  - type: markdown
    attributes:
      value: |
        <!-- action: close -->
        Return to idle state. 👉 Just click **Submit new issue**, no other input required.
