name: Feed the cat
description: Start a feeding challenge (Find the Bug). Just click Submit, no typing needed.
title: Feed the cat
labels: ['game-action']
body:
  - type: markdown
    attributes:
      value: |
        <!-- action: feed -->
        I'm starting the feed challenge. 👉 Just click **Submit new issue**, no other input required.
