name: Force update the cat mood
description: Tired of waiting? You can force the cat mood update. Just click Submit — no typing needed.
title: Force update the cat mood
labels: ['game-action']
body:
  - type: markdown
    attributes:
      value: |
        <!-- action: force-update-mode -->
        I want some challenge now. 👉 Just click **Submit new issue** — no other input required.
