name: Pick option 3
description: Confirm picking option 3. Just click Submit, no typing needed.
title: Pick option 3
labels: ['game-action']
body:
  - type: markdown
    attributes:
      value: |
        <!-- action: pick-option-3 -->
        I confirm I choose Option 3. 👉 Just click **Submit new issue**, no other input required.
